#ifndef MINI_PUPPER_GAIT_CENTER_OF_CURVATURE_H_INCLUDED
#define MINI_PUPPER_GAIT_CENTER_OF_CURVATURE_H_INCLUDED

namespace mini_pupper
{



};

#endif // MINI_PUPPER_GAIT_CENTER_OF_CURVATURE_H_INCLUDED
