teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
      z: 4
    scale_linear:
      x: 0.2
      y: 0.1
      z: 0.03
    scale_linear_turbo:
      x: 0.33
      y: 0.2
      z: 0.03

    axis_angular:
      pitch: 7
      roll: 6
      yaw: 3
    scale_angular:
      pitch: 0.15
      roll: 0.15
      yaw: 1.0
    scale_angular_turbo:
      pitch: 0.30
      roll: 0.30
      yaw: 2.0

    require_enable_button: true
    enable_button: 4  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button